services:

  zed:
    image: ${ZED_X_IMAGE:-zed-x:latest}
    build:
      context: .
      dockerfile: ${ZED_DOCKERFILE:-Zedx/Dockerfile}
    runtime: nvidia
    privileged: true
    network_mode: host
    stdin_open: true
    tty: true
    environment:
      - DISPLAY=${DISPLAY:-:1}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - XAUTHORITY=/root/.Xauthority
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY:-0}
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}
    volumes:
      - ${XAUTHORITY:-/tmp/.docker.xauth}:/root/.Xauthority:ro
      - /dev/video0:/dev/video0
      - /dev/bus/usb:/dev/bus/usb
      - /dev/nvhost-ctrl:/dev/nvhost-ctrl
      - /dev/nvhost-ctrl-isp:/dev/nvhost-ctrl-isp
      - /dev/nvhost-prof-gpu:/dev/nvhost-prof-gpu
      - /dev/nvhost-nvjpg:/dev/nvhost-nvjpg
      - /dev/nvhost-vic:/dev/nvhost-vic
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/nvidia/nvcam/settings/:/var/nvidia/nvcam/settings/
      - /var/nvidia/nvcam/status/:/var/nvidia/nvcam/status/
      - /etc/systemd/system/zed_x_daemon.service:/etc/systemd/system/zed_x_daemon.service
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/robo/zed_docker_ai/:/usr/local/zed/resources/
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: >-
      /bin/bash -c "echo \"building\" &&
      source /opt/ros/humble/setup.bash &&
      source /root/ros2_ws/install/setup.bash &&
      ros2 launch zed_wrapper zed_camera.launch.py camera_model:=zedx"

  loone:
    image: ${LOON_E_IMAGE:-loon-e:latest}
    build:
      context: .
      dockerfile: ${LOONE_DOCKERFILE:-LoonE/Dockerfile}
    runtime: nvidia
    privileged: true
    network_mode: host
    stdin_open: true
    tty: true
    depends_on:
      - zed
    environment:
      - DISPLAY=${DISPLAY:-:1}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - XAUTHORITY=/root/.Xauthority
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY:-0}
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev:/dev
      - /tmp:/tmp
      - /home/robo:/home/robo
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: /bin/bash -c "echo \"building\ at $(pwd)\" &&
      source /opt/ros/humble/setup.bash &&
      source /root/Loon-E/install/setup.bash &&
      ros2 launch loon_e_coms coms_launch.py"
